version: '3'

services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build:
      context: ./backend
    user: node:node
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - node_modules_volume:/usr/src/app/node_modules

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env

volumes:
  postgres_data:
    name: "postgres_data"
  node_modules_volume:
    name: "node_modules_volume"
