
# Use a base image
FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your backend will be running on
EXPOSE 3000

# Define the command to start your backend
CMD [ "npm", "run", "start:dev" ]